services:
  reverse-proxy:
    container_name: magpie-monitor-reverse-proxy
    image: nginxproxy/nginx-proxy:1.6
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
    ports:
      - "443:443"
      - "80:80"
  acme-companion:
    container_name: magpie-monitor-acme-companion
    image: nginxproxy/acme-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    volumes_from:
      - reverse-proxy:rw
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}

volumes:
  certs:
  html:
  acme:

networks:
  default:
    name: magpie-network
    external: true
