services:
  logs-ingestion-service:
    user: "0"
    container_name: magpie-monitor-test-logs-ingestion-service
    build:
      context: ./go
      dockerfile: ./docker/logs_ingestion/Dockerfile
      target: tests
      # args:
      #   - LOGSDB_PORT=${LOGSDB_PORT}
      #   - LOGSDB_HOST=${LOGSDB_HOST}
      #   - LOGSDB_USER=${LOGSDB_USER}
      #   - LOGSDB_PASSWORD=${LOGSDB_PASSWORD}
      #   - LOGSDB_CERT_PATH=${LOGSDB_CERT_PATH}
      #   - LOGS_INGESTION_QUEUE_HOST=${LOGS_INGESTION_QUEUE_HOST}
      #   - LOGS_INGESTION_QUEUE_PORT=${LOGS_INGESTION_QUEUE_PORT}
      #   - LOGS_INGESTION_QUEUE_USERNAME=${KAFKA_CLIENT_USERNAME}
      #   - LOGS_INGESTION_QUEUE_PASSWORD=${KAFKA_CLIENT_PASSWORD}
    environment:
      - LOGSDB_PORT=${LOGSDB_PORT}
      - LOGSDB_HOST=${LOGSDB_HOST}
      - LOGSDB_USER=${LOGSDB_USER}
      - LOGSDB_PASSWORD=${LOGSDB_PASSWORD}
      - LOGSDB_CERT_PATH=${LOGSDB_CERT_PATH}
      - LOGS_INGESTION_QUEUE_HOST=${LOGS_INGESTION_QUEUE_HOST}
      - LOGS_INGESTION_QUEUE_PORT=${LOGS_INGESTION_QUEUE_PORT}
      - LOGS_INGESTION_QUEUE_USERNAME=${KAFKA_CLIENT_USERNAME}
      - LOGS_INGESTION_QUEUE_PASSWORD=${KAFKA_CLIENT_PASSWORD}
      - APP_ENV=test

    volumes:
      - es-certs:/usr/local/share
      - cache:/go/pkg/mod/

volumes:
  cache:
  es-certs:
    external: true

networks:
  default:
    name: magpie-network
    external: true
