services:
  # logs-ingestion-service-test:
  #   user: "0"
  #   container_name: magpie-monitor-test-logs-ingestion-service
  #   build:
  #     context: ./go
  #     dockerfile: ./docker/logs_ingestion/Dockerfile
  #     target: tests
  #   environment:
  #     - APP_ENV=test
  #     - LOGSDB_PORT=${LOGSDB_PORT}
  #     - LOGSDB_HOST=${LOGSDB_HOST}
  #     - LOGSDB_USER=${LOGSDB_USER}
  #     - LOGSDB_PASSWORD=${LOGSDB_PASSWORD}
  #     - LOGSDB_CERT_PATH=${LOGSDB_CERT_PATH}
  #     - LOGS_INGESTION_QUEUE_HOST=${LOGS_INGESTION_QUEUE_HOST}
  #     - LOGS_INGESTION_QUEUE_PORT=${LOGS_INGESTION_QUEUE_PORT}
  #     - LOGS_INGESTION_QUEUE_USERNAME=${KAFKA_CLIENT_USERNAME}
  #     - LOGS_INGESTION_QUEUE_PASSWORD=${KAFKA_CLIENT_PASSWORD}
  #     - LOGS_INGESTION_NODE_LOGS_TOPIC=${LOGS_INGESTION_NODE_LOGS_TOPIC}
  #     - LOGS_INGESTION_APPLICATION_LOGS_TOPIC=${LOGS_INGESTION_APPLICATION_LOGS_TOPIC}
  #     - KAFKA_BROKER_GROUP_ID=${KAFKA_BROKER_GROUP_ID}
  #     - INTEGRATION_TEST_WAIT_MODIFIER=${INTEGRATION_TEST_WAIT_MODIFIER}
  #   volumes:
  #     - es-certs:/usr/local/share
  #     - cache:/go/pkg/mod/
  reports-service-test:
    user: "0"
    container_name: magpie-monitor-test-reports-service
    image: magpiemonitor/reports-service
    build:
      context: ./go
      dockerfile: ./docker/reports/Dockerfile
      target: tests
    volumes:
      - es-certs:/usr/local/share
      - cache:/go/pkg/mod/
    environment:
      - APP_ENV=test
      - INTEGRATION_TEST_WAIT_MODIFIER=${INTEGRATION_TEST_WAIT_MODIFIER}
      - REPORTSDB_USER=${REPORTSDB_USER}
      - REPORTSDB_PASSWORD=${REPORTSDB_PASSWORD}
      - REPORTSDB_HOST=${REPORTSDB_HOST}
      - REPORTSDB_PORT=${REPORTSDB_PORT}
      - REPORTSDB_NAME=test-reports
      - REPORTS_SERVICE_PORT=${REPORTS_SERVICE_PORT}
      - LOGSDB_PORT=${LOGSDB_PORT}
      - LOGSDB_HOST=${LOGSDB_HOST}
      - LOGSDB_USER=${LOGSDB_USER}
      - LOGSDB_PASSWORD=${LOGSDB_PASSWORD}
      - LOGSDB_CERT_PATH=${LOGSDB_CERT_PATH}
      - REPORTS_OPENAI_API_KEY=${REPORTS_OPENAI_API_KEY}
      - REPORTS_OPENAI_API_URL=${REPORTS_OPENAI_API_URL}
      - REPORTS_OPENAI_API_MODEL=${REPORTS_OPENAI_API_MODEL}
      - REPORTS_OPENAI_BATCH_SIZE_BYTES=${REPORTS_OPENAI_BATCH_SIZE_BYTES}
      - REPORTS_OPENAI_CONTEXT_SIZE_BYTES=${REPORTS_OPENAI_CONTEXT_SIZE_BYTES}
      - REPORTS_OPENAI_MODEL_TEMPERATURE=${REPORTS_OPENAI_MODEL_TEMPERATURE}
      - REPORTS_OPENAI_POLLING_INTERVAL_SECONDS=${REPORTS_OPENAI_POLLING_INTERVAL_SECONDS}
      - REPORTS_BATCH_AWAITING_INTERVAL_SECONDS=${REPORTS_BATCH_AWAITING_INTERVAL_SECONDS}
      - REPORTS_POLLING_INTERVAL_SECONDS=${REPORTS_POLLING_INTERVAL_SECONDS}
      - REPORTS_PENDING_BATCH_REDIS_URL=${REPORTS_PENDING_BATCH_REDIS_URL}
      - REPORTS_PENDING_BATCH_REDIS_PASSWORD=${REPORTS_PENDING_BATCH_REDIS_PASSWORD}
      - REPORTS_PENDING_BATCH_REDIS_DB=${REPORTS_PENDING_BATCH_REDIS_DB}
      - MESSAGE_BROKER_USERNAME=${MESSAGE_BROKER_USERNAME}
      - MESSAGE_BROKER_PASSWORD=${MESSAGE_BROKER_PASSWORD}
      - MESSAGE_BROKER_ADDRESS=${MESSAGE_BROKER_ADDRESS}
      - KAFKA_MAX_MESSAGE_SIZE_BYTES=${KAFKA_MAX_MESSAGE_SIZE_BYTES}
      - KAFKA_BROKER_GROUP_ID=magpie-monitor-test
      - REPORT_GENERATED_BROKER_TOPIC=${REPORT_GENERATED_BROKER_TOPIC}
      - REPORT_REQUEST_FAILED_BROKER_TOPIC=${REPORT_REQUEST_FAILED_BROKER_TOPIC}
      - REPORT_REQUESTED_BROKER_TOPIC=${REPORT_REQUESTED_BROKER_TOPIC}
      - REPORTS_MAX_IN_PRORESS_TOKENS=${REPORTS_MAX_IN_PRORESS_TOKENS}
      - REPORTS_MAX_OPENAI_OUTPUT_COMPLETION_TOKENS=${REPORTS_MAX_OPENAI_OUTPUT_COMPLETION_TOKENS}
      - SWAGGER_HOST=${REPORTS_SERVICE_HOST}
      - VIRTUAL_HOST=${REPORTS_PRODUCTION_HOST}
      - LETSENCRYPT_HOST=${REPORTS_PRODUCTION_HOST}
      - VIRTUAL_PORT=${REPORTS_SERVICE_PORT}

volumes:
  cache:
  es-certs:
    external: true

networks:
  default:
    name: magpie-network
    external: true
