agent:
  node:
    enabled: true
    service:
      port: 8080
      targetPort: 8080
    files:
      - /var/log/calico/cni/cni.log
  cluster:
    enabled: true
    friendlyName: magpie-cloud-dev-cluster
    excludedNamespaces:
      - kube-system
    service:
      port: 8080
      targetPort: 8080
  redis:
    enabled: true
    password: redispass
    port: 6379
  remoteWrite:
    metadata:
      url: google.com
    logs:
      url: <URL>
      username: <username>
      password: <password>
      clusterTopic: pods
      nodesTopic: nodes
      batchSize: 5
