agent:
  friendlyName: magpie-cloud-dev-cluster
  application:
    enabled: true
    image: magpiemonitor/agent
    excludedNamespaces:
      - kube-system
  node:
    enabled: true
    image: magpiemonitor/agent 
    files:
      - /var/log/calico/cni/cni.log
      - /var/log/magpie-monitor/journal.log
  redis:
    enabled: true # Set enabled: false if running custom Redis instance
    image: redis:6
    url: <URL> # Fill in if running custom Redis instance 
    database: <DATABASE> # Fill in if running custom Redis instance
    password: <PASSWORD> # Fill in with safe password of your choice
  remoteWrite:
    metadata:
      url: <URL>
      clientSecret: <SECRET>
    logs:
      url: <URL>
      username: <USERNAME>
      password: <PASSWORD>
