{{ if .Values.agent.application.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magpie-agent-cluster
  namespace: {{ .Release.Namespace }}
  labels:
    name: magpie-agent-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: magpie-agent-cluster
  template:
    metadata:
      labels:
        name: magpie-agent-cluster
    spec:
      containers:
        - name: magpie-agent-cluster
          image: {{ .Values.agent.application.image }}
          command: [ "./bin/server" ]
          args:
            {{ include "agent.pod.config" . | indent 12 | trim }}
            {{ include "redis.connection" . | indent 12 | trim }}
            {{ include "metadata.scrapeIntervals" . | indent 12 | trim }}
            {{ include "broker.connection" . | indent 12 | trim }}
            {{ include "agent.pod.excludedNamespaces" . | indent 12 | trim }}
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
      terminationGracePeriodSeconds: 30
      serviceAccountName: magpie-agent-service-account
{{ end }}