apiVersion: apps/v1
kind: Deployment
metadata:
  name: magpie-agent-cluster
  namespace: {{ .Values.agent.namespace }}
  labels:
    name: magpie-agent-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      name: magpie-agent-cluster
  template:
    metadata:
      labels:
        name: magpie-agent-cluster
    spec:
      containers:
        - name: magpie-agent-cluster
          image: alpine
          ports:
            - containerPort: 80