services:
  prometheus:
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    ports:
      - "9099:9099"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3001"
    environment:
      VIRTUAL_HOST: ${GRAFANA_PRODUCTION_HOST}
      LETSENCRYPT_HOST: ${GRAFANA_PRODUCTION_HOST}
      VIRTUAL_PORT: 3001
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
