{{ if .Values.agent.node.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: magpie-agent-node
  namespace: {{ .Release.Namespace }}
  labels:
    name: magpie-agent-node
spec:
  selector:
    matchLabels:
      name: magpie-agent-node
  template:
    metadata:
      labels:
        name: magpie-agent-node
    spec:
      containers:
        # TODO - add resources, QOS
        - name: magpie-agent-node
          image: woojciech/agent:latest
          command: [ "./bin/server" ]
          args:
            - "--clusterFriendlyName"
            - {{ .Values.agent.cluster.friendlyName | quote }}
            - "--scrape"
            - "nodes"
            - "--nodeRemoteWriteMetadataUrl"
            - {{ .Values.agent.remoteWrite.metadata.url | quote }}
            - "--redisUrl"
            - "magpie-agent-redis.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.agent.redis.port }}"
            - "--redisDatabase"
            - "0"
            - "--redisPassword"
            - {{ .Values.agent.redis.password | quote }}
            - "--logScrapeIntervalSeconds"
            - "60"
            - "--metadataScrapeIntervalSeconds"
            - "60"
            {{- with .Values.agent.remoteWrite.logs }}
            - "--remoteWriteBrokerUrl"
            - {{ .url | quote }}
            - "--remoteWriteNodeTopic"
            - {{ .nodesTopic | quote }}
            - "--remoteWriteBatchSize"
            - {{ .batchSize | quote }}
            - "--remoteWriteBrokerUsername"
            - {{ .username | quote }}
            - "--remoteWriteBrokerPassword"
            - {{ .password | quote }}
            {{- end }}
            {{- range $file := .Values.agent.node.files }}
            - "--file"
            - "{{$file}}"
            {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
          {{- range $file := .Values.agent.node.files }}
            - name: {{ splitList "/" $file | last | replace "." "-" }}
              mountPath: {{ $file }}
              readOnly: true
          {{- end }}
      terminationGracePeriodSeconds: 30
      volumes:
      {{- range $file := .Values.agent.node.files }}
        - name: {{ splitList "/" $file | last | replace "." "-" }}
          hostPath:
            path: {{$file}}
      {{- end }}
{{ end }}