{{ if .Values.agent.node.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: magpie-agent-node
  namespace: {{ .Release.Namespace }}
  labels:
    name: magpie-agent-node
spec:
  selector:
    matchLabels:
      name: magpie-agent-node
  template:
    metadata:
      labels:
        name: magpie-agent-node
    spec:
      containers:
        - name: magpie-agent-node
          image: {{ .Values.agent.node.image }}
          command: [ "./bin/server" ]
          args:
            {{ include "agent.node.config" . | indent 12 | trim }}
            {{ include "redis.connection" . | indent 12 | trim }}
            {{ include "metadata.scrapeIntervals" . | indent 12 | trim }}
            {{ include "broker.connection" . | indent 12 | trim }}
            {{ include "agent.node.watchedFiles" . | indent 12 | trim }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            {{ include "agent.node.volumeMounts" . | indent 12 | trim }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
      terminationGracePeriodSeconds: 30
      volumes:
        {{ include "agent.node.volumes" . | indent 8 | trim }}
{{ end }}