openapi: 3.0.0
info:
  title: Logs API
  version: 1.0.0
paths:
  /logs:
    post:
      summary: Create or return logs from a node
      operationId: createLogs
      responses:
        "200":
          description: A NodeLogs object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NodeLogs"
      requestBody:
        description: Log creation request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NodeLogs"
components:
  schemas:
    NodeLogs:
      type: object
      properties:
        timestamp:
          type: integer
          format: uint32
          description: The timestamp when the log was created
          example: 1634112000
        host:
          type: string
          description: The hostname or IP of the node
          example: "node-123.example.com"
        message:
          type: string
          description: The log message
