{{ if .Values.agent.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: magpie-agent-redis
  labels:
    name: magpie-agent-redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    name: magpie-agent-redis
{{ end }}